#!/bin/sh -e

case "${1}" in
  install)
    cat << EOF > /etc/xdg/autostart/piwiz.desktop
[Desktop Entry]
Type=Application
Name=Raspberry Pi First-Run Wizard
Exec=sh -c 'gsettings set org.gnome.mutter center-new-windows true; sudo -AE piwiz'
StartupNotify=true
EOF
    ;;

  abort-upgrade|upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`${1}'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
