#!/bin/sh

# set up autologin
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $1 --noclear %I \$TERM
EOF
sed /etc/lightdm/lightdm.conf -i -e "s/^\(#\|\)autologin-user=.*/autologin-user=$1/"

# remove the autostart for the wizard
rm -f /etc/xdg/autostart/piwiz.desktop

# set up a self-deleting autostart to delete the wizard user
cat > /etc/xdg/autostart/deluser.desktop << EOF
[Desktop Entry]
Type=Application
Name=Delete Wizard User
NoDisplay=true
Exec=sh -c 'sudo userdel -r rpi-first-boot-wizard; sudo rm /etc/sudoers.d/010_wiz-nopasswd; sudo rm /etc/xdg/autostart/deluser.desktop'
EOF
