#!/bin/sh

if [ -z $SUDO_USER ] ; then
    PAUID=$(id -u $USER)
else
    PAUID=$(id -u $SUDO_USER)
fi

SINKS=$(sudo -u "#$PAUID" XDG_RUNTIME_DIR=/run/user/$PAUID pactl list short sinks)
DOUT=$(echo $SINKS | grep -oE bcm2835_audio\\.digital\\-stereo)
HOUT=$(echo $SINKS | grep -oE [0-9a-f]{8,}\\.hdmi\\.[0-9a-z]+\\-stereo | head -n 1)

if ! [ -z $DOUT ] ; then 
    OUTPUT=$DOUT
elif ! [ -z $HOUT ] ; then 
    OUTPUT=$HOUT
else 
    OUTPUT=bcm2835_audio.analog-stereo 
fi
sudo -u "#$PAUID" XDG_RUNTIME_DIR=/run/user/$PAUID pactl set-default-sink alsa_output.platform-$OUTPUT
sudo -u "#$PAUID" XDG_RUNTIME_DIR=/run/user/$PAUID pactl set-sink-volume alsa_output.platform-$OUTPUT 100%
