#!/bin/sh

# rename the user
usermod --login $2 --home /home/$2 --move-home $1
groupmod --new-name $2 $1

# set the password
echo "$2:$3" | chpasswd -e

# remove no-password sudo for old user
SUDOFILE=$(grep -l $1.*NOPASSWD /etc/sudoers.d/*)
rm $SUDOFILE

# add no-password sudo for new user
cat > /etc/sudoers.d/010_$2-nopasswd << EOF
$2 ALL=(ALL) NOPASSWD: ALL
EOF

# set up autologin
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $2 --noclear %I \$TERM
EOF
sed /etc/lightdm/lightdm.conf -i -e "s/^\(#\|\)autologin-user=.*/autologin-user=$2/"

# remove the autostart for the wizard
rm -f /etc/xdg/autostart/piwiz.desktop

# set up a self-deleting autostart to delete the wizard user
cat > /etc/xdg/autostart/deluser.desktop << EOF
[Desktop Entry]
Type=Application
Name=Delete Wizard User
NoDisplay=true
Exec=sh -c 'sudo userdel -r rpi-first-boot-wizard; sudo rm /etc/sudoers.d/010_wiz-nopasswd; sudo rm /etc/xdg/autostart/deluser.desktop'
EOF
