#!/bin/sh

# create the first boot user
sudo adduser rpi-first-boot-wizard --gecos ',,,,' --add_extra_groups --quiet --disabled-password > /dev/null
sudo adduser rpi-first-boot-wizard adm --quiet > /dev/null
sudo adduser rpi-first-boot-wizard sudo --quiet > /dev/null
sudo adduser rpi-first-boot-wizard input --quiet > /dev/null
sudo adduser rpi-first-boot-wizard netdev --quiet > /dev/null
echo "rpi-first-boot-wizard ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/010_wiz-nopasswd > /dev/null

# set autologin
sudo systemctl set-default graphical.target
sudo ln -fs /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service
echo "[Service]\nExecStart=\nExecStart=-/sbin/agetty --autologin rpi-first-boot-wizard --noclear %I \$TERM" | sudo tee /etc/systemd/system/getty@tty1.service.d/autologin.conf > /dev/null
sudo sed /etc/lightdm/lightdm.conf -i -e "s/^\(#\|\)autologin-user=.*/autologin-user=rpi-first-boot-wizard/"

# create the wizard autostart...
echo "[Desktop Entry]\nType=Application\nName=Raspberry Pi First-Run Wizard\nExec=sudo -AE piwiz --useronly $USER\nStartupNotify=true" | sudo tee /etc/xdg/autostart/piwiz.desktop > /dev/null

echo "Rebooting - please wait..."
sync
reboot
